name: Build with `native-tls`
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenSSL libraries
        run: sudo apt update && sudo apt install libssl-dev
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build Bob
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --profile optimized --no-default-features --features native-tls
      - name: Check lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose -- -D warnings
      - name: Upload Bob Linux binary
        uses: actions/upload-artifact@v2
        with:
          name: "bob-linux-x86_64-native_tls"
          path: "target/optimized/bob"
          if-no-files-found: error
          retention-days: 7

